const List<Map<String, String>> buildings = [
{"id": "1", "building": "A", "name": "Edificio Administrativo", "areas": '• Dirección\n• Departamento De Vinculación\n• Oficina De Oficialidad Paqueteria\n• Departamento De Desarrollo Academico\n• Recursos Humanos\n• Servicio Medico\n• Departamento De Servicios Escolares\n• Departamento de Comunicacion y Difusion\n• Recursos Financieros\n• DEP: Division de Estudios Profesionales\n• DEPI: Division de Estudios de Posgrado e Investigacion' , "photo": 'assets/A.jpeg', "related": 'administracion enfermeria doctor emergencias medicina pagos pagar colegiatura correos paquetes envios direccion vinculacion'},
{"id": "2", "building": "B", "name": "Laboratorio De Química Analítica", "photo": 'assets/B.jpeg', "related": 'quimica analitica'},
{"id": "3", "building": "C", "name": "Coordinación De Ingles", "areas": '• C1 C2 C3 C4 C5\n• Centro de lenguas extranjeras' ,"photo": 'assets/C.jpeg', "related": 'coordinacion idiomas frances aleman cle teachers lenguajes'},
{"id": "4", "building": "CH", "name": "Departamento De Ingeniera Industrial Y Bioquímica", "areas": '• CH1 CH2 CH3 CH4 CH5 CH6\n• Cubiculos Ingenieria Industrial\n• Capitulos Estudiantiles\n• Sala de Usos Multiples\n• Sala Memorial\n• Sala de Tutorias\n• Laboratorio de Ingenieria Industrial' , "photo": 'assets/CH.jpeg', "related": 'bioquimica empresas emprender emprendedor'},
{"id": "5", "building": "D", "name": "Laboratorio De Ingeniera Bioquímica", "areas": '• D1 D2 D3 D4 D5 D6', "photo": 'assets/D.jpeg', "related": 'bioquimica'},
{"id": "6", "building": "E", "name": "Aulas Y Taller De Dibujo", "areas": '• E1 E2 E3 E4 E5 E6\n• Laboratorio de Dibujo Tecnico Mecanica', "photo": 'assets/E.jpeg', "related": 'dibujo tecnico dibujo asistido por computadora dibujo digital autocad solid works'},
{"id": "7", "building": "F", "name": "Sala Audiovisual No. 1 Y Aulas", "areas": '• F1 F2 F3 F4 F5 F6\n• Sala Audiovisual\n• Oficina de Titulacion', "photo": 'assets/F.jpeg', "related": 'audiovisual 1 sala 1'},
{"id": "8", "building": "G", "name": "Laboratorio Ing. Mecánica Y Eléctrica", "areas": '• Laboratorio de Electrica\n• Laboratorio de Mecanica', "photo": 'assets/G.jpeg', "related": 'ingenieria mecanica ingenieria electrica ingenieria mecatronica'},
{"id": "9", "building": "H", "name": "Unidad Deportiva Y Tribunas", "photo": 'assets/H.jpeg', "related": 'deportes futbol football basquetball basketbol basketball baloncesto educacion fisica atletismo canchas gradas escaleras partidos'},
{"id": "10", "building": "I", "name": "Departamento De Sistemas Y Computación", "areas": '• Nodo de Internet\n• Titulación\n• Residencias Profesionales\n• Créditos Complementarios\n• Comisión Dictaminadora\n• Jefatura Sistemas\n• Sala de Juntas\n• Cubiculos Sistemas\n• Laboratorio de Ingenieria de Software\n• Laboratorio de Tecnologias Web\n• Laboratorio de Redes', "photo": 'assets/I.jpeg', "related": 'departamento sistemas departamento tics departartamento computacion computadoras titulacion creditos complementarios comision dictaminadora macs apple cisco routers servidores backrooms'},
{"id": "11", "building": "J", "name": "Aulas De Titulación Y PADHIE", "areas": '• J0 J1 J2 J3\n• J4 • FAS\n• Sala 1 y 2\n• Campana de Titulación', "photo": 'assets/J.jpeg', "related": 'la fas fabrica de software aulas de titulacion campana de titulacion graduacion graduado'},
{"id": "12", "building": "K", "name": "Aulas Y Delegación Sindical", "areas": '• K1 K2 K3 K4 K5 K6 K7 K8 K9\n• Delegacion Sindical', "photo": 'assets/K.jpeg', "related": 'ingenieria en sistemas tics'},
{"id": "13", "building": "L", "name": "Aulas Licenciatura Administración", "areas": '• L1 L2 L3 L4 L5\n• L6 L7 L8 L9 L10 L11', "photo": 'assets/L.jpeg', "related": 'licenciatura en administracion licenciados'},
{"id": "14", "building": "LL", "name": "Centro de Negocios", "areas": '• Sala A\n• Sala B\n• Sala C\n• Jefe de Departamento\n• Centro de Incubacion e Inovacion Empresarial\n• Oficina de Servicio Social y Desarrollo Comunitario', "photo": 'assets/LL.jpeg', "related": 'conferencias platicas'},
{"id": "15", "building": "M", "name": "Departamento Económico Administrativo", "areas": '• M1 M2\n• Banco de Proyectos Licenciatura en Administracion\n• DEA Jefatura de Proyectos de Vinculacion\n• DCEA Depertamento de Ciencias Economico Administrativas', "photo": 'assets/M.jpeg', "related": 'departamento economico administrativo administracion'},
{"id": "16", "building": "N", "name": "Laboratorios De Ingeniería Bioquímica", "areas": '• Archivo De Concentración\n• Laboratorio De Operaciones Unitarias\n• Departamento De Mantenimiento De Equipo', "photo": 'assets/N.jpeg', "related": 'ingenieria bioquimica laboratorios bioquimica biologia ciencias'},
{"id": "17", "building": "Ñ", "name": "Laboratorio Instrumentación Analítica", "areas": '• Ñ1 Ñ2 Ñ3 Ñ4 Ñ5', "photo": 'assets/N_.jpeg', "related": 'laboratorio instrumentacion analitica'},
{"id": "18", "building": "O", "name": "Laboratorio Químico Biológico", "areas": '• Laboratorio De Bioquimica\n• Anexo Laboratorio Quimico Biologicas', "photo": 'assets/O.jpeg', "related": 'Laboratorio Quimico Biologico biologia ciencias'},
{"id": "19", "building": "P", "name": "Laboratorio De Física", "areas": '• Laboratorio De Electromagnetismo\n• Laboratorio De Estatica Y Dinamica', "photo": 'assets/P.jpeg', "related": 'laboratorio fisica ciencias'},
{"id": "20", "building": "Q", "name": "Aulas Electrónica" ,"areas": '• Q1 Q2 Q3 Q4 Q5 Q6', "photo": 'assets/Q.jpeg', "related": 'electronica electrica'},
{"id": "21", "building": "R", "name": "Cafetería", "photo": 'assets/R.jpeg', "related": 'cafeteria arriba almuerzo almorzar comer comida tienda mesas comedor mesitas hambre comedor'},
{"id": "22", "building": "S", "name": "Departamento De Recursos Materiales Y Servicios", "photo": 'assets/S.jpeg'},
{"id": "23", "building": "S1", "name": "Consejo Estudiantil", "photo": 'assets/S1.jpeg', "related": 'consejales'},
{"id": "24", "building": "S2", "name": "Comedor para trabajadores", "photo": 'assets/S2.jpeg'},
{"id": "25", "building": "S3", "name": "Caldera Demostrativa (laboratorio)", "areas": '• Baños', "photo": 'assets/S3.jpeg'},
{"id": "26", "building": "T", "name": "Laboratorio De Ingeniería Mecánica II", "areas": '• Sistema Integrado de Manufactura\n• Laboratorio de Neumática\n• Metrología', "photo": 'assets/T.jpeg', "related": 'ingenieria mecanica 2 laboratorio mecanica 2 laboratorio neumatica laboratorio metrologia'},
{"id": "27", "building": "U", "name": "Gimnasio Auditorio", "areas": '• Auditorio Heber Soto Fierro\n• Cancha de Basquetball\n• Oficina Promoción Cultural\n• Coordinación Cultural\n• Banda de Guerra\n• Papeleria\n• Gimnasio\n• Música\n• AADC: Apreciación de las Artes y División Cultural', "photo": 'assets/U.jpeg', "related": 'deportes basquetball basketbol basketball baloncesto educacion fisica atletismo canchas gradas escaleras partidos'},
{"id": "28", "building": "V", "name": "Departamento De Actividades Extraescolares", "areas": '• V1 V2 V3', "photo": 'assets/V.jpeg'},
{"id": "29", "building": "W", "name": "Editorial" ,"areas": '• IEEE', "photo": 'assets/W.jpeg'},
{"id": "30", "building": "X", "name": "Comedor Estudiantil", "photo": 'assets/X.jpeg', "related": 'cafeteria abajo almuerzo almorzar comer comida tienda mesas comedor mesitas hambre'},
{"id": "31", "building": "Y", "name": "Departamento De Ing. Electrónica", "areas": '• Y1: Laboratorio de Potencia\n• Y2: Laboratorio de Control\n• Y3: Laboratorio de PLCs\n• Y4: Laboratorio de Impresos\n• Y5: Laboratorio de Procesos\n• Y6: Laboratorio de Electrónica Analógica I\n• Y7: Laboratorio de Electrónica Analógica II\n• Y8: Laboratorio de Sistemas Digitales\n• Grabado Térmico\n• Fotolitografía\n• Serigrafía\n• Departamento de Ingeniería Electrónica', "photo": 'assets/Y.jpeg', "related": 'ingenieria electronica electrica'},
{"id": "32", "building": "Z", "name": "Aulas de Ing. Eléctrica" , "photo": 'assets/Z.jpeg', "related": 'ingenieria electronica electrica'},
{"id": "33", "building": "AA", "name": "Departamento de Ingeniería Eléctrica" , "photo": 'assets/AA.jpeg', "related": 'ingenieria electrica electronica'},
{"id": "34", "building": "AB", "name": "Cubículos de Ing. Electrónica" , "photo": 'assets/AB.jpeg', "related": 'cubiculos ingenieria electronica electrica'},
{"id": "35", "building": "AC", "name": "Depto. de Ciencias Básicas", "photo": 'assets/AC.jpeg', "related": 'departamento ciencias basicas'},
{"id": "36", "building": "AD", "name": "Cubículos para Prof. de Ciencias Básicas" ,"photo": 'assets/AD.jpeg', "related": 'cubiculos de ciencias basicas'},
{"id": "37", "building": "AE", "name": "Laboratorios de Maestría en Electrónica" , "photo": 'assets/AE.jpeg', "related": 'maestria electronica electrica'},
{"id": "38", "building": "AF", "name": "Centro de Información" , "areas": '• Jefatura del Centro de Información\n• Oficina de Organización Biblíografica\n• Acervo De consulta\n• Cubiculos uso general\n• Cubiculo Asesorias\n• Sala institucional\n• Sala de lectura\n• Sala de internet\n• Hemeroteca\n• Videoteca\n• Acervo General\n• Laboratorio de idiomas\n• Catálogos\n• Copiadora\n• Inglés\n• Centro de consulta\n• BBL', "photo": 'assets/AF.jpeg', "related": 'centro de informacion organizacion bibliografica catalogos ingles'},
{"id": "39", "building": "AG", "name": "Educ. a Dist, Aulas de Computo, Posgrado Mecánica", "areas": '• AGPG\n• LC1 LC2 LC3\n• AG1 AG2 AG3 AG4 AG5 AG6 AG7 AG8\n• Laboratorio AG\n• Apoyo Psicologico\n• Centro de Computo\n• Coordinacion de Laboratorios\n• Oficinas Posgrado Mecanica\n• Laboratorio de Modelacion Computacional' , "photo": 'assets/AG.jpeg', "related": 'educacion a distancia posgrado mecanica psicologo psicologia salud metal computadoras computacion pcs'},
{"id": "40", "building": "AH", "name": "Depto. de Bioquímica y Laboratorios", "areas": '• Recepción\n• Cubiculos docentes\n• Almacen de materiales y reactivos', "photo": 'assets/AH.jpeg', "related": 'departamento bioquimica ingenieria bioquimica cubiculos bodega aurrera'},
{"id": "41", "building": "2A", "name": "Depto. Ing. Mecánica y Posg. en Materiales", "photo": 'assets/2A.jpeg', "related": 'departamento mecanica posgrado materiales'},
{"id": "42", "building": "2B", "name": "Laboratorio de Fusión al Vacío", "photo": 'assets/2B.jpeg', "related": 'fusion al vacio'},
{"id": "43", "building": "2C", "name": "Almacén de Materias Primas", "photo": 'assets/2C.jpeg', "related": 'almacen materias primas'},
{"id": "44", "building": "2D", "name": "Laboratorio de Fundición y trat. Térmicos", "photo": 'assets/2D.jpeg', "related": 'laboratorio fundicion tratamientos termicos'},
{"id": "45", "building": "2E", "name": "Aula", "photo": 'assets/2E.jpeg'},
{"id": "46", "building": "2F", "name": "Depto. de Ing. en Materiales", "photo": 'assets/2F.jpeg', "related": 'departamento materiales ingenieria en materiales'},
{"id": "47", "building": "2G", "name": "Lab. de análisis Químicos y Fisicoquímica", "photo": 'assets/2G.jpeg', "related": 'laboratorio analisis quimicos laboratorio fisicoquimica quimica'},
{"id": "48", "building": "2H", "name": "Laboratorio de Materiales", "photo": 'assets/2H.jpeg'},
{"id": "49", "building": "2J", "name": "Laboratorio de Rayos X", "photo": 'assets/2J.jpeg'},
{"id": "50", "building": "2K", "name": "Aulas", "photo": 'assets/2J.jpeg'},
{"id": "51", "building": "3A", "name": "Laboratorio de Posgrado en Eléctrica", "photo": 'assets/3A.jpeg', "related": 'posgrado electrica'},
{"id": "52", "building": "3B", "name": "Cubículos Doctorado en Eléctrica", "photo": 'assets/3B.jpeg', "related": 'cubiculos electrica cubiculos doctorado electrica'},
];

const List<Map<String, String>> schoolEvents = [
  {
    'title': 'InnovaTecNM',
    'date': 'Mayo 25, 2023',
    'location': 'Auditorio Heber Soto',
    'description':
    'CUMBRE NACIONAL DE DESARROLLO TECNOLÓGICO, \nINVESTIGACIÓN E INNOVACIÓN \nETAPA LOCAL: CERTAMEN DE PROYECTOS',
    'imageUrl': 'assets/images/science_fair.jpg',
  },
  {
    'title': 'Feria del Libro',
    'date': 'Mayo 28, 2023',
    'location': 'Arcotecho',
    'description':
    'Ven a la nueva feria del libro en el tec',
    'imageUrl': 'assets/images/math_olympiad.jpg',
  },
  {
    'title': 'Conferencias Servicio Social',
    'date': 'Junio 2, 2023',
    'location': 'Centro de Negocios',
    'description':
    'Asiste a la conferencia este 2 de junio para alistarte para el servicio social',
    'imageUrl': 'assets/images/spelling_bee.jpg',
  },
  {
    'title': 'Mimixekua',
    'date': 'Mayo 23, 2023',
    'location': 'Auditorio Heber Soto',
    'description':
    'Our talented musicians will perform a variety of genres in this annual music festival. Come enjoy an evening of entertainment!',
    'imageUrl': 'assets/images/music_festival.jpg',
  },
];

