const List<Map<String, String>> buildings = [
{"id": "1", "building": "A", "name": "Edificio Administrativo"},
{"id": "2", "building": "B", "name": "Laboratorio De Química Analítica"},
{"id": "3", "building": "C", "name": "Coordinación De Ingles"},
{"id": "4", "building": "CH", "name": "Departamento De Ingeniera Industrial Y Bioquímica"},
{"id": "5", "building": "D", "name": "Laboratorio De Ingeniera Bioquímica"},
{"id": "6", "building": "E", "name": "Aulas Y Taller De Dibujo"},
{"id": "7", "building": "F", "name": "Sala Audiovisual No. 1 Y Aulas"},
{"id": "8", "building": "G", "name": "Laboratorio Ing. Mecánica Y Eléctrica"},
{"id": "9", "building": "H", "name": "Unidad Deportiva Y Tribunas"},
{"id": "10", "building": "I", "name": "Departamento De Sistemas Y Computación"},
{"id": "11", "building": "J", "name": "Aulas De Titulación Y PADHIE"},
{"id": "12", "building": "K", "name": "Aulas Y Delegación Sindical"},
{"id": "13", "building": "L", "name": "Aulas Licenciatura Administración"},
{"id": "14", "building": "LL", "name": "Centro de Negocios"},
{"id": "15", "building": "M", "name": "Departamento Económico Administrativo"},
{"id": "16", "building": "N", "name": "Laboratorios De Ingeniería Bioquímica"},
{"id": "17", "building": "Ñ", "name": "Laboratorio Instrumentación Analítica"},
{"id": "18", "building": "O", "name": "Laboratorio Químico Biológico"},
{"id": "19", "building": "P", "name": "Laboratorio De Física"},
{"id": "20", "building": "Q", "name": "Aulas Electrónica"},
{"id": "21", "building": "R", "name": "Cafetería"},
{"id": "22", "building": "S", "name": "Departamento De Recursos Materiales Y Servicios"},
{"id": "23", "building": "S1", "name": "Consejo Estudiantil"},
{"id": "24", "building": "S2", "name": "Comedor para trabajadores"},
{"id": "25", "building": "S3", "name": "Caldera Demostrativa (laboratorio)"},
{"id": "26", "building": "T", "name": "Laboratorio De Ingeniería Mecánica II"},
{"id": "27", "building": "U", "name": "Gimnasio Auditorio"},
{"id": "28", "building": "V", "name": "Departamento De Actividades Extraescolares"},
];
